config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  resources :post_comments
  resources :comments
  get 'search/index'

  get 'pages/about'

  get 'pages/contact'

  get 'pages/resources'

  devise_for :admin_users, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self) rescue true 
  resources :categories
  resources :categories
  resources :categories
  resources :categories
  resources :categories
  get 'categories/index'

  get 'categories/edit'

  get 'categories/new'

  get 'categories/show'

  get 'home/index'
    
    resources :posts
    resources :categories
    resources :search
    
    match '/about', :to => 'pages#about', via: :all
    match '/contact', :to => 'pages#contact', via: :all
    match '/resources', :to => 'pages#resources', via: :all

    root 'home#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
    
    def create
        AA.create(aa_params)
    end
    
    private
    
    def aa_params
        params.require(:aa).permit(:name, :email, :password, :password_confirmation, :remember_me)
    end
    has_many :posts
end

app/models/category.rb
class Category < ActiveRecord::Base
    def create
        Category.create(category_params)
    end
    
    private
    
    def category_params
        params.require(:category).permit(:name)
    end
    has_many :posts
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
    
    validates_presence_of :name
    validates_length_of :name, :within=> 2..20
    validates_presence_of :body
end

app/models/post.rb
class Post < ActiveRecord::Base
    def create
        Post.create(poss_params)
    end
    
    private
    
    def poss_params
        params.require(:post).permit(:title, :body, :category_id, :admin_user_id)
    end
    belongs_to :category
    belongs_to :admin_user
    has_many :post_comment, :dependent => :destroy
    validates :title, :presence => true
    validates_length_of :body, :minimum => 10
    
#    def self.search(search)
#        where("title ILIKE ?", "%#{search}%") 
#        where("body ILIKE ?", "%#{search}%")
#    end
   
end

app/models/post_comment.rb
class PostComment < ActiveRecord::Base
  belongs_to :post
    
    validates_presence_of :name
    validates_length_of :name, :within=> 2..20
    validates_presence_of :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :search_default
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    helper_method :all_categories
    helper_method :all_posts
    
    def all_categories
        @categories = Category.all
    end
    
    def all_posts
        @posts = Post.all
    end
    
    
    def search_default
        @q = Post.ransack(params[:q])
    end
    
    def post_params
        params.require(:post).permit(:title, :body, :category_id)
    end
end

app/controllers/categories_controller.rb
    class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
      @category = Category.find(params[:id])
      @title = @category.name
      @post = @category.posts
  end

 
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/comments_controller.rb
class CommentsController < InheritedResources::Base
    
    def create
        @comment = Comment.new(comment_params)
        
        if @comment.save
            flash[:notice] = 'Comment was successfully Created.'
            redirect_to(@comment.post)
        else
            flash[:notice] = "Error Creating post comment : #{@post_comment.errors}"
            redirect_to(@post_comment.post)
        end
    end

    private
    def comment_params
      params.require(:comment).permit(:name, :email, :body, :post_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
      @posts = Post.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end

  def resources
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
        @post = Post.all
    end
    
    def show
        @post = Post.find(params[:id])
        @user = AdminUser.all
        @comment = PostComment.new(:post => @post)
    end
    
    def new
        @post = Post.new
        @category = Category.all
    end
    
    def create
#        @post = Post.new(params[:post])
        @post = Post.create(post_params)
        if @post.save
            redirect_to posts_path, :notice => "Your post has been saved"
        else
            render "new"
        end
    end
    
    def edit
        @post = Post.find(params[:id])
    end
    
    def update
#        @post = Post.create(post_params)
        @post = Post.find(params[:id])
        if @post.update_attributes(post_params)
            redirect_to posts_path, :notice => "Your Post Has Been Updated"
        else
            render "edit"
        end
    end
    
    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to posts_path, :notice => "Your Post Has Been Deleted"
    end
    
    def post_params
        params.require(:post).permit(:title, :body, :category_id)
    end
    
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
      @result = @q.result(distinct: true)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/application.html.erb
<%= render "partials/header" %>

          <div id="page">
           <div id="page-bgtop">
            <div id="page-bgbtm">
             <div id="content">
                <div class="flash-message">
                    <% flash.each do |key,value| %>
                        <p><%= value %></p>
                    <% end %>
                </div>
                <%= yield %>

            
              <div style="clear: both;">&nbsp;</div>
             </div>
             <!-- end #content -->
                

  <%= render "partials/sidebar" %>   
    
  
             <!-- end #sidebar -->

                
   
             
             <div style="clear: both;">&nbsp;</div>

            </div>
           </div>
          </div>
          <!-- end #page-->
          <div id="footer">
           <p>&copy; 2016, MASARIUMAN | Arif Setiawan</p>
          </div>
          <!-- en #footer-->
         </div>
         <!-- end #wrapper-->
    </body>
</html>

app/views/pages/about.html.erb
<div class="post"><h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>
</div>

app/views/pages/contact.html.erb
<div class="post"><h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p></div>

app/views/pages/resources.html.erb
<div class="post"><h1>Pages#resources</h1>
<p>Find me in app/views/pages/resources.html.erb</p>
</div>

app/views/partials/_comment.html.erb
<div class="comment">
    <i><%= comment.name %> Says : </i><Br />
    <%= comment.body %>
    <br />
    <hr>
</div>

app/views/partials/_header.html.erb
<!DOCTYPE html>
<html>
    <head>
      <title>Myrubyblog</title>
        <link href="http://fonts.googleapis.com/css?family=Abel" rel="stylesheet" type="text/css" />
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
    </head>
    <div id="templatemo_header">                                             
    <body>                                                           
        <div id="wrapper">
          <div id="header-wrapper">
           <div id="header">
            <div id="logo">
             <h1><a href="#">My Ruby Blog</a></h1>
             <p>Learing Ruby on Rails</p>
            </div>
            <div id="menu">
                <ul class="main-nav">
                    <li><%= link_to "Home", root_path %></li>
                    <li><%= link_to "About", about_path %></li>
                    <li><%= link_to "Blog", posts_path %></li>
                    <li><%= link_to "Contact", contact_path %></li>
                    <li><%= link_to "Resource", resources_path %></li>
                </ul>
            </div>
           </div>
          </div>
          <!-- end #header -->

app/views/partials/_sidebar.html.erb
    <div id="sidebar">
        <ul>
            <li>
                <div id="search">
                    
                    
                    
                    
                    
                    
                    <%= search_form_for @q, url: "/search", role: "search" , method: 'get' do |f| %>                  
                    <%= f.text_field :title_or_body_cont %>
                    <%= f.submit "Search" %>
                    <% end %>
                    
                    
                    
                
                    
                    
                    
                </div>                                                                                     
                <div style="clear: both;">&nbsp;</div>
               </li>
               <li>
                <h2>Get The Framework</h2>
                <p>You can download Ruby and/or Ruby on Rails for free right now
                 <br>
                 <a style="color:#D93544" href="http://rubyonrails.org/download"></a></p>
               </li>
               <li>
                <h2>Categories</h2>
                <ul>
                    <% all_categories.each do |cat| %>
                        <li><%= link_to cat.name,category_path(:id => cat.id) %></li>
                    <% end %>
                </ul>
               </li>
               <li>
                <h2>Blogroll</h2>
                <ul>
                    <% all_posts.each do |post| %>
                        <li><%= link_to post.title,category_path(:id => post.id) %></li>
                    <% end %>
                </ul>
               </li>
          </ul>
     </div>