config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  resources :post_comments
  resources :comments
  get 'search/index'

  get 'pages/about'

  get 'pages/contact'

  get 'pages/resources'

  devise_for :admin_users, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self) rescue true 
  resources :categories
  resources :categories
  resources :categories
  resources :categories
  resources :categories
  get 'categories/index'

  get 'categories/edit'

  get 'categories/new'

  get 'categories/show'

  get 'home/index'
    
    resources :posts
    resources :categories
    resources :search
    
    match '/about', :to => 'pages#about', via: :all
    match '/contact', :to => 'pages#contact', via: :all
    match '/resources', :to => 'pages#resources', via: :all

    root 'home#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
    
    def create
        AA.create(aa_params)
    end
    
    private
    
    def aa_params
        params.require(:aa).permit(:name, :email, :password, :password_confirmation, :remember_me)
    end
    has_many :posts
end

app/models/category.rb
class Category < ActiveRecord::Base
    def create
        Category.create(category_params)
    end
    
    private
    
    def category_params
        params.require(:category).permit(:name)
    end
    has_many :posts
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_content_type :data, :content_type => /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
    
    validates_presence_of :name
    validates_length_of :name, :within=> 2..20
    validates_presence_of :body
end

app/models/post.rb
class Post < ActiveRecord::Base
    def create
        Post.create(poss_params)
    end
    
    private
    
    def poss_params
        params.require(:post).permit(:title, :body, :category_id, :admin_user_id)
    end
    belongs_to :category
    belongs_to :admin_user
    has_many :post_comment, :dependent => :destroy
    validates :title, :presence => true
    validates_length_of :body, :minimum => 10
    
#    def self.search(search)
#        where("title ILIKE ?", "%#{search}%") 
#        where("body ILIKE ?", "%#{search}%")
#    end
   
end

app/models/post_comment.rb
class PostComment < ActiveRecord::Base
  belongs_to :post
    
    validates_presence_of :name
    validates_length_of :name, :within=> 2..20
    validates_presence_of :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :search_default
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    helper_method :all_categories
    helper_method :all_posts
    
    def all_categories
        @categories = Category.all
    end
    
    def all_posts
        @posts = Post.all
    end
    
    
    def search_default
        @q = Post.ransack(params[:q])
    end
    
    def post_params
        params.require(:post).permit(:title, :body, :category_id)
    end
end

app/controllers/categories_controller.rb
    class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
      @category = Category.find(params[:id])
      @title = @category.name
      @post = @category.posts
  end

 
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/comments_controller.rb
class CommentsController < InheritedResources::Base
    
    def create
        @comment = Comment.new(comment_params)
        
        if @comment.save
            flash[:notice] = 'Comment was successfully Created.'
            redirect_to(@comment.post)
        else
            flash[:notice] = "Error Creating post comment : #{@post_comment.errors}"
            redirect_to(@post_comment.post)
        end
    end

    private
    def comment_params
      params.require(:comment).permit(:name, :email, :body, :post_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
      @posts = Post.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end

  def resources
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < InheritedResources::Base

     
    def create
        @post_comment = PostComment.new(post_comment_params)
        
        if @post_comment.save
            flash[:notice] = 'Comment was successfully Created.'
            redirect_to(@post_comment.post)
        else
            flash[:notice] = "Error Creating post comment : #{@post_comment.errors}"
            redirect_to(@post_comment.post)
        end
    end
    
    private
    def post_comment_params
      params.require(:post_comment).permit(:name, :email, :body, :post_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
        @post = Post.all
    end
    
    def show
        @post = Post.find(params[:id])
        @user = AdminUser.all
        @comment = PostComment.new(:post => @post)
    end
    
    def new
        @post = Post.new
        @category = Category.all
    end
    
    def create
#        @post = Post.new(params[:post])
        @post = Post.create(post_params)
        if @post.save
            redirect_to posts_path, :notice => "Your post has been saved"
        else
            render "new"
        end
    end
    
    def edit
        @post = Post.find(params[:id])
    end
    
    def update
#        @post = Post.create(post_params)
        @post = Post.find(params[:id])
        if @post.update_attributes(post_params)
            redirect_to posts_path, :notice => "Your Post Has Been Updated"
        else
            render "edit"
        end
    end
    
    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to posts_path, :notice => "Your Post Has Been Deleted"
    end
    
    def post_params
        params.require(:post).permit(:title, :body, :category_id)
    end
    
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
      @result = @q.result(distinct: true)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/categories/index.html.erb
<div class="post">
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<ul>
    <% @categories.each do |category| %>
        <li><%= link_to category.name, category%></li>
    <% end %>
</ul>
</div>

app/views/categories/show.html.erb
<% if @post.each do |post| %>
<div class="post">
    <h2 class="title"><%= link_to post.title,post %></h2>
    <div class="entry"><%= post.body %></div>
    <div class="byline">
        <p class="meta">May 07, 2012 Posted by <a href="#">Someone</a></p>
        <p class="links"><a href="post.html">Read More</a> BLAH BLAH BLAH</p>
    </div>
</div>
<% end.empty? %>
<div class="post">
    <p>Sorry, There are no posts in this category</p>
</div>
<% end %>
<div class="post"><%= link_to "Go Back to Categories", categories_path %></div>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.text_field :post_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Body</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.name %></td>
        <td><%= comment.email %></td>
        <td><%= comment.body %></td>
        <td><%= comment.post %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @comment.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @comment.email %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Post:</strong>
  <%= @comment.post %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/post_comments/_form.html.erb
<%= form_for(@post_comment) do |f| %>
  <% if @post_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post_comment.errors.count, "error") %> prohibited this post_comment from being saved:</h2>

      <ul>
      <% @post_comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.text_field :post_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/post_comments/edit.html.erb
<h1>Editing Post Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @post_comment %> |
<%= link_to 'Back', post_comments_path %>

app/views/post_comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Post Comments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Body</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @post_comments.each do |post_comment| %>
      <tr>
        <td><%= post_comment.name %></td>
        <td><%= post_comment.email %></td>
        <td><%= post_comment.body %></td>
        <td><%= post_comment.post %></td>
        <td><%= link_to 'Show', post_comment %></td>
        <td><%= link_to 'Edit', edit_post_comment_path(post_comment) %></td>
        <td><%= link_to 'Destroy', post_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post comment', new_post_comment_path %>

app/views/post_comments/new.html.erb
<h1>New Post Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', post_comments_path %>

app/views/post_comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @post_comment.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @post_comment.email %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post_comment.body %>
</p>

<p>
  <strong>Post:</strong>
  <%= @post_comment.post %>
</p>

<%= link_to 'Edit', edit_post_comment_path(@post_comment) %> |
<%= link_to 'Back', post_comments_path %>

app/views/posts/index.html.erb
<% @post.each do |post| %>
 
<div class="post">
    
    <h2 class="title"><%= link_to post.title,post %></h2>
    <div class="entry"><%= post.body %></div>
    <div class="byline">
        <p class="meta"><%= post.created_at.strftime("%b %d, %Y") %> Posted by <%= post.admin_user.name %></p>
        <p class="links"><%= link_to "Read More",post %></p>
    </div>
</div>
<% end %>










<!--
<h3>Sample Post One</h3>
<p>This is some sample text for our awasome new ruby blog</p>
<hr>
<h3>Sample Post Two</h3>
<p>This is more sample text for our awasome new ruby blog</p>-->

app/views/posts/show.html.erb
<div class="post">
    
<h1><%= @post.title %></h1>
<small><%= @post.created_at.strftime("%b %d, %Y") %></small>
    <small><p>Created By : <%= @post.admin_user.name %></p></small>
<p><%= @post.body %></p>

Category: <%= link_to @post.category.name,category_path(:id => @post.category.id) %><br />

<%= link_to "Go Back",posts_path %>

    <hr>
    <%= form_for @comment do |f| %>
        <%= f.hidden_field :post_id %>
        <p>
            <%= f.label :name %><br />
            <%= f.text_field :name %>
        </p>
        <p>
            <%= f.label :email %><br />
            <%= f.text_field :email %>
        </p>
        <p>
            <%= f.label :body %><br />
            <%= f.text_area :body %>
        </p>
        <p>
            <%= f.submit "Post Comment" %>
        </p>
    <% end %>
    <br />
    
    <%= render :partial => "partials/comment", :collection => @post.post_comment %>

</div>

<!--<h1>Sample Post</h1>-->